version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    target-branch: "develop"
    groups:
      radix-ui:
        patterns:
          - "@radix-ui/*"
      sentry:
        patterns:
          - "@sentry/*"
      testing:
        patterns:
          - "@testing-library/*"
          - "@types/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "develop"
