services:
  tts-frontend:
    container_name: tts_frontend
    build:
      context: .
      dockerfile: deploy/Dockerfile.frontend
      target: dev
    volumes:
      - ./apps/frontend/src:/usr/src/tts-fe/src
      - ./apps/frontend/public:/usr/src/tts-fe/public
    ports:
      - 3100:3100
    env_file:
      - .env

  tts-frontend-prod:
    container_name: tts_frontend_prod
    build:
      context: .
      dockerfile: deploy/Dockerfile.frontend
      target: prod
      args:
        - TTS_FE_VARS_METHOD=dotenv
        - TTS_FE_DOTENV_FILE=.env
    volumes:
      - ./apps/frontend/src:/usr/src/tts-fe/src
      - ./apps/frontend/public:/usr/src/tts-fe/public
    ports:
      - 3100:80

networks:
  default:
    name: tts-docker-network
