version: '3'
services:
  tts-frontend:
    container_name: tts_frontend
    build:
      context: .
    volumes:
      - ./src:/usr/src/tts-fe/src
      - ./public:/usr/src/tts-fe/public
    ports:
      - 3100:3000
    environment:
      PORT: 3000
      CHOKIDAR_USEPOLLING: 'true'
    env_file:
      - .env

networks:
  default:
    external:
      name: tts_bridge
