FROM node:21-alpine3.19 AS build

RUN mkdir -p /usr/src/tts-fe
WORKDIR /usr/src/tts-fe

COPY .*rc ./
COPY *.json ./
COPY .prettier* ./
COPY *.config.js ./
COPY *.config.ts ./

RUN npm install

COPY public/ public/
COPY src/ src/
COPY index.html ./

RUN npm run build

FROM nginx:alpine

COPY --from=build /usr/src/tts-fe/build /usr/share/nginx/html
COPY nginx.tts.conf /etc/nginx/conf.d/default.conf

