services:
  tts-frontend:
    container_name: tts_frontend
    build:
      context: ../..
      dockerfile: apps/frontend/Dockerfile
      target: dev
    volumes:
      - ./src:/usr/src/tts/apps/frontend/src
      - ./public:/usr/src/tts/apps/frontend/public
    ports:
      - 3100:3100
    env_file:
      - path: .env
        required: false

  tts-frontend-prod:
    container_name: tts_frontend_prod
    build:
      context: ../..
      dockerfile: apps/frontend/Dockerfile
      target: prod
      args:
        - TTS_FE_VARS_METHOD=dotenv
        - TTS_FE_DOTENV_FILE=apps/frontend/.env
    ports:
      - 3100:80

networks:
  default:
    name: tts-docker-network
