# Generated by Django 5.1.4 on 2025-02-16 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=10)),
                ('course_type', models.CharField(max_length=2)),
                ('year', models.IntegerField()),
                ('url', models.CharField(max_length=2000)),
                ('plan_url', models.CharField(max_length=2000)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'course',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('acronym', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'faculty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('professor_acronym', models.CharField(blank=True, max_length=32, null=True)),
                ('professor_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'professor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('lesson_type', models.CharField(max_length=3)),
                ('day', models.IntegerField()),
                ('start_time', models.DecimalField(decimal_places=1, max_digits=3)),
                ('duration', models.DecimalField(decimal_places=1, max_digits=3)),
                ('location', models.CharField(max_length=31)),
                ('is_composed', models.IntegerField()),
                ('professor_id', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'slot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=16)),
                ('url', models.CharField(max_length=2000)),
                ('semester', models.IntegerField()),
                ('year', models.SmallIntegerField()),
                ('schedule_url', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('last_updated', models.DateTimeField()),
                ('hash', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.course')),
            ],
            options={
                'db_table': 'course_unit',
                'managed': True,
                'unique_together': {('id', 'course', 'year', 'semester')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.faculty'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('last_updated', models.DateTimeField()),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courseunit')),
            ],
            options={
                'db_table': 'class',
                'managed': True,
                'unique_together': {('name', 'course_unit')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('id', 'faculty', 'year')},
        ),
        migrations.CreateModel(
            name='CourseMetadata',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='university.course')),
                ('course_unit_year', models.IntegerField()),
                ('ects', models.FloatField()),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courseunit')),
            ],
            options={
                'db_table': 'course_metadata',
                'managed': True,
                'unique_together': {('course', 'course_unit', 'course_unit_year')},
            },
        ),
        migrations.CreateModel(
            name='SlotClass',
            fields=[
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='university.slot')),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, to='university.class')),
            ],
            options={
                'db_table': 'slot_class',
                'managed': True,
                'unique_together': {('slot', 'class_field')},
            },
        ),
        migrations.CreateModel(
            name='SlotProfessor',
            fields=[
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='university.slot')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.professor')),
            ],
            options={
                'db_table': 'slot_professor',
                'managed': True,
                'unique_together': {('slot', 'professor')},
            },
        ),
    ]
