# Generated by Django 5.1.4 on 2025-06-04 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.course')),
            ],
            options={
                'db_table': 'course_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseUnitCourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.coursegroup')),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.courseunit')),
            ],
            options={
                'db_table': 'course_unit_course_group',
                'managed': True,
                'unique_together': {('course_unit', 'course_group')},
            },
        ),
    ]
