# Generated by Django 5.1.4 on 2025-09-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_coursegroup_courseunitcoursegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='vacancies',
            field=models.IntegerField(default=None, null=True, blank=True),
        ),
    ]
