# Generated by Django 5.1.12 on 2026-01-03 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_class_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotclass',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.slot', unique=False),
        ),
        migrations.AddField(
            model_name='slotclass',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
            preserve_default=False
        ),
        migrations.AlterUniqueTogether(
            name='slotclass',
            unique_together={('slot', 'class_field')},
        ),
    ]
