# Generated by Django 5.1.4 on 2025-02-16 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUnitEnrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nmec', models.CharField(max_length=32)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('admin_state', models.CharField(max_length=32)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course_unit_enrollments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DirectExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_name', models.CharField(max_length=256)),
                ('issuer_nmec', models.CharField(max_length=32)),
                ('accepted', models.BooleanField()),
                ('canceled', models.BooleanField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('admin_state', models.CharField(max_length=32)),
                ('hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'db_table': 'direct_exchange',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExchangeAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'exchange_admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExchangeUrgentRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nmec', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=2048)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('admin_state', models.CharField(max_length=32)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'db_table': 'exchange_urgent_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_name', models.CharField(max_length=256)),
                ('issuer_nmec', models.CharField(max_length=32)),
                ('accepted', models.BooleanField()),
                ('canceled', models.BooleanField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('admin_state', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'marketplace_exchange',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseUnitEnrollmentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolling', models.BooleanField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courseunit')),
                ('course_unit_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exchange.courseunitenrollments')),
            ],
            options={
                'db_table': 'course_unit_enrollment_options',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DirectExchangeParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=256)),
                ('participant_nmec', models.CharField(max_length=32)),
                ('class_participant_goes_from', models.CharField(max_length=16)),
                ('class_participant_goes_to', models.CharField(max_length=16)),
                ('course_unit', models.CharField(max_length=64)),
                ('course_unit_id', models.CharField(max_length=16)),
                ('accepted', models.BooleanField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('direct_exchange', models.ForeignKey(db_column='direct_exchange', on_delete=django.db.models.deletion.DO_NOTHING, to='exchange.directexchange')),
            ],
            options={
                'db_table': 'direct_exchange_participants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExchangeAdminCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.course')),
                ('exchange_admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exchange.exchangeadmin')),
            ],
            options={
                'db_table': 'exchange_admin_courses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExchangeAdminCourseUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courseunit')),
                ('exchange_admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exchange.exchangeadmin')),
            ],
            options={
                'db_table': 'exchange_admin_course_units',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExchangeExpirations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courseunit')),
            ],
            options={
                'db_table': 'exchange_expirations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExchangeUrgentRequestOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_user_goes_from', models.CharField(max_length=16)),
                ('class_user_goes_to', models.CharField(max_length=16)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courseunit')),
                ('exchange_urgent_request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exchange.exchangeurgentrequests')),
            ],
            options={
                'db_table': 'exchange_urgent_request_options',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='directexchange',
            name='marketplace_exchange',
            field=models.ForeignKey(blank=True, db_column='marketplace_exchange', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exchange.marketplaceexchange'),
        ),
        migrations.CreateModel(
            name='MarketplaceExchangeClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_unit_name', models.CharField(max_length=256)),
                ('course_unit_acronym', models.CharField(max_length=256)),
                ('course_unit_id', models.CharField(max_length=256)),
                ('class_issuer_goes_from', models.CharField(max_length=16)),
                ('class_issuer_goes_to', models.CharField(max_length=16)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('marketplace_exchange', models.ForeignKey(db_column='marketplace_exchange', on_delete=django.db.models.deletion.DO_NOTHING, to='exchange.marketplaceexchange')),
            ],
            options={
                'db_table': 'marketplace_exchange_class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentCourseMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmec', models.CharField(max_length=255)),
                ('fest_id', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.course')),
            ],
            options={
                'db_table': 'student_course_metadata',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserCourseUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nmec', models.CharField(max_length=32)),
                ('class_field', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.DO_NOTHING, to='university.class')),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='university.courseunit')),
            ],
            options={
                'db_table': 'user_course_units',
                'managed': True,
            },
        ),
    ]
