# Generated by Django 5.1.4 on 2025-03-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directexchange',
            name='admin_state',
            field=models.CharField(default='untreated', max_length=32),
        ),
        migrations.AlterField(
            model_name='marketplaceexchange',
            name='admin_state',
            field=models.CharField(default='untreated', max_length=32),
        ),
    ]
