# Generated by Django 5.1.4 on 2025-06-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_courseunitenrollmentoptions_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangeurgentrequestoptions',
            old_name='class_user_goes_from',
            new_name='class_issuer_goes_from',
        ),
        migrations.RenameField(
            model_name='exchangeurgentrequestoptions',
            old_name='class_user_goes_to',
            new_name='class_issuer_goes_to',
        ),
        migrations.RenameField(
            model_name='exchangeurgentrequests',
            old_name='user_nmec',
            new_name='issuer_nmec',
        ),
        migrations.AddField(
            model_name='exchangeurgentrequests',
            name='issuer_name',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
