# Generated by Django 5.1.4 on 2025-09-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_exchangeexpirations_is_course_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeurgentrequests',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='marketplaceexchange',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
