# Generated by Django 5.1.12 on 2025-09-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_alter_exchangeurgentrequests_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directexchange',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
