# Generated by Django 5.1.4 on 2025-08-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_alter_directexchange_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='directexchange',
            name='last_validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
