# Generated by Django 5.1.12 on 2025-12-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_directexchange_last_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseunitenrollments',
            name='user_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
