import { MajorCourses } from '../@types'

export const coursesData: MajorCourses = [
  [
    {
      course_unit_id: 484400,
      course: 'L.EIC007',
      name: 'Análise Matemática II',
      acronym: 'AM II',
      url: 'https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=484400',
      course_year: 1,
      semester: 2,
      year: 2021,
      schedule_url: 'https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=484400 ',
      last_updated: '2022-02-19T14:43:27Z',
    },
    {
      course_unit_id: 484401,
      course: 'L.EIC008',
      name: 'Física I',
      acronym: 'F I',
      url: 'https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=484401',
      course_year: 1,
      semester: 2,
      year: 2021,
      schedule_url: 'https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=484401 ',
      last_updated: '2022-02-19T14:43:27Z',
    },
    {
      course_unit_id: 484423,
      course: 'L.EIC010',
      name: 'Teoria da Computação',
      acronym: 'TC',
      url: 'https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=484423',
      course_year: 1,
      semester: 2,
      year: 2021,
      schedule_url: 'https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=484423 ',
      last_updated: '2022-02-19T14:43:27Z',
    },
    {
      course_unit_id: 484399,
      course: 'L.EIC006',
      name: 'Arquitetura de Computadores',
      acronym: 'AC',
      url: 'https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=484399',
      course_year: 1,
      semester: 2,
      year: 2021,
      schedule_url: 'https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=484399 ',
      last_updated: '2022-02-19T14:43:27Z',
    },
    {
      course_unit_id: 484422,
      course: 'L.EIC009',
      name: 'Programação',
      acronym: 'P',
      url: 'https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=484422',
      course_year: 1,
      semester: 2,
      year: 2021,
      schedule_url: 'https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=484422 ',
      last_updated: '2022-02-19T14:43:27Z',
    },
  ],
  [
    {
      course_unit_id: 484426,
      course: 'L.EIC018',
      name: 'Laboratório de Computadores',
      acronym: 'LC',
      url: 'https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=484426',
      course_year: 2,
      semester: 2,
      year: 2021,
      schedule_url: 'https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=484426 ',
      last_updated: '2022-02-19T14:43:27Z',
    },
    {
      course_unit_id: 484427,
      course: 'L.EIC019',
      name: 'Linguagens e Tecnologias Web',
      acronym: 'LTW',
      url: 'https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=484427',
      course_year: 2,
      semester: 2,
      year: 2021,
      schedule_url: 'https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=484427 ',
      last_updated: '2022-02-19T14:43:27Z',
    },
    {
      course_unit_id: 484424,
      course: 'L.EIC016',
      name: 'Desenho de Algoritmos',
      acronym: 'DA',
      url: 'https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=484424',
      course_year: 2,
      semester: 2,
      year: 2021,
      schedule_url: 'https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=484424 ',
      last_updated: '2022-02-19T14:43:27Z',
    },
    {
      course_unit_id: 484425,
      course: 'L.EIC017',
      name: 'Engenharia de Software',
      acronym: 'ES',
      url: 'https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=484425',
      course_year: 2,
      semester: 2,
      year: 2021,
      schedule_url: 'https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=484425 ',
      last_updated: '2022-02-19T14:43:27Z',
    },
    {
      course_unit_id: 484428,
      course: 'L.EIC020',
      name: 'Métodos Estatísticos',
      acronym: 'ME',
      url: 'https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=484428',
      course_year: 2,
      semester: 2,
      year: 2021,
      schedule_url: 'https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=484428 ',
      last_updated: '2022-02-19T14:43:27Z',
    },
  ],
  [
    {
      course_unit_id: 484381,
      course: 'L.EIC028',
      name: 'Computação Paralela e Distribuída',
      acronym: 'CPD',
      url: 'https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=484381',
      course_year: 3,
      semester: 2,
      year: 2021,
      schedule_url: 'https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=484381 ',
      last_updated: '2022-02-19T14:43:27Z',
    },
    {
      course_unit_id: 484379,
      course: 'L.EIC026',
      name: 'Compiladores',
      acronym: 'C',
      url: 'https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=484379',
      course_year: 3,
      semester: 2,
      year: 2021,
      schedule_url: 'https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=484379 ',
      last_updated: '2022-02-19T14:43:27Z',
    },
    {
      course_unit_id: 484380,
      course: 'L.EIC027',
      name: 'Computação Gráfica',
      acronym: 'CG',
      url: 'https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=484380',
      course_year: 3,
      semester: 2,
      year: 2021,
      schedule_url: 'https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=484380 ',
      last_updated: '2022-02-19T14:43:27Z',
    },
    {
      course_unit_id: 484443,
      course: 'L.EIC030',
      name: 'Projeto Integrador',
      acronym: 'PI',
      url: 'https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=484443',
      course_year: 3,
      semester: 2,
      year: 2021,
      schedule_url: 'https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=484443 ',
      last_updated: '2022-02-19T14:43:27Z',
    },
    {
      course_unit_id: 484442,
      course: 'L.EIC029',
      name: 'Inteligência Artificial',
      acronym: 'IA',
      url: 'https://sigarra.up.pt/feup/pt/ucurr_geral.ficha_uc_view?pv_ocorrencia_id=484442',
      course_year: 3,
      semester: 2,
      year: 2021,
      schedule_url: 'https://sigarra.up.pt/feup/pt/hor_geral.ucurr_view?pv_ocorrencia_id=484442 ',
      last_updated: '2022-02-19T14:43:27Z',
    },
  ],
]
