name: Code analysis

on:
  pull_request:
    branches:
      - develop
      - main
    types: [ready_for_review, synchronize, opened, reopened]

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: Lint

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Lint Code
        run: npm run lint

  vitest:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: Vitest and RTL tests

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: CI=true npm run test-coverage
    